### PR TITLE
NOTICE file should not have executable permissions

### PR DESCRIPTION
**Pull request by musicinmybrain**

### CODE REVIEW

**Review by rleigh-codelibre — APPROVED** [review]
Thanks, this looks fine to me.

**Comment by musicinmybrain** [comment]
Looks like a CI job timed out for reasons presumably unreleated to the PR. Does that normally happen?

**Comment by rleigh-codelibre** [comment]
Not normally, but this codebase isn't especially actively developed.  The timeout was on the Travis CI Mac builds, so likely an issue with the Travis service (they have changed their service for open source projects recently and it now takes much longer than previously, not sure if that's a coincidence or not).

**Comment by rleigh-codelibre** [comment]
On further inspection, looks like it was scheduled OK but timed out downloading stuff.  I've merged the PR anyway--the failure was irrelevant.  If it turns out the config is outdated I'll update it in a separate PR.  It may be that the Travis Mac config needs some changes.

**Pull request merged**
