### PR TITLE
Apply outstanding fixes

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
This is a collection of small changes carried by most distributors on top of the last release.  All have had quite a lot of testing in Debian, FreeBSD ports, Homebrew, vcpkg and other package repositories.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Merged to permit further development with these fixes in place.  A point release can be made with these fixes in place to allow all the downstream consumers to drop their patchsets.  Is anyone aware of additional patches which need applying?

**Comment by bblough** [comment]
There are a couple of autotools related patches (XALANC-757, XALANC-771) but I expect those don't matter if we're switching to CMAKE (unless we want to continue supporting autotools also)

**Comment by rleigh-codelibre** [comment]
No reason we can't pick them up in the interim.  While Xerces-C has retained both build systems, the Autotools build in Xerces-C is quite well done, while the Xalan-C Autotools support is pretty poor with `Makefile.incl`, `runConfigure`, no Autoconf options usage and no Automake usage.  Because of that degree of non-standard usage, I won't personally have any time to dedicate to it.  Unless anyone really wants to maintain this, I don't see the same amount of value in retaining it.

**Comment by bblough** [comment]
I agree with regard to the quality of the autotools support.  I think if we were to support it going forward, I would want to redo it to address the things you mentioned (among others).  While I'd be willing to commit to doing it, it wouldn't be in the immediate future as I don't have the availability right now.

**Pull request merged**
